### ISSUE TITLE
.

### ISSUE THREAD

**Issue by heeheejj** [DEVSTU-kor-developers/devstu-issue#3]
.

**Comment by winterlood** [comment]
확인하였습니다.
내일중으로 개인페이지는 구글에서 수집하지않도록 처리하겠습니다.
아이디를 메일로 보내주시면 구글검색결과에서 바로 제외신청 하겠습니다!
불편을 드려 죄송합니다

**Comment by kjyk0310** [comment]
아이디 kjyk0835@naver.com
입니다!
구글에서 kjyk0835라고 쳤을 때 뜨더라구요..
피드백 감사합니다!!
 
-----Original Message-----

**Comment by winterlood** [comment]
URL삭제 요청하였습니다

[image: image.png]
[image: image.png]

>
